# Generated by Django 4.1.7 on 2023-04-14 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('DNI', 'DNI'), ('passport', 'passport'), ('driver license', 'driver license')], max_length=20, null=True)),
                ('document_identifier', models.CharField(blank=True, max_length=30, null=True)),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='document_front')),
                ('back_image', models.ImageField(blank=True, null=True, upload_to='document_back')),
                ('status', models.CharField(choices=[('not uploaded', 'not uploaded'), ('uploaded', 'uploaded'), ('approved', 'approved'), ('rejected', 'rejected')], default='not uploaded', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
