# Generated by Django 4.1.7 on 2023-04-30 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategoria', 'verbose_name_plural': 'Subcategorias'},
        ),
    ]
