# Generated by Django 4.1.7 on 2023-05-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mercado_link',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
