# Generated by Django 4.1.7 on 2023-05-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_mercado_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remainder_sended',
            field=models.BooleanField(default=False),
        ),
    ]
